# Generated by Django 4.2.1 on 2023-06-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=800)),
                ('description', models.CharField(max_length=400)),
                ('category', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
