# Generated by Django 4.2.1 on 2023-06-07 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watch_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
